server:
  port: 8090

logging: 
  level:
    root: INFO
    com.github.elgleidson.demo.test: DEBUG

spring:
  application:
    name: Demo-Test
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: demo
    password: 
  jpa:
    database: h2
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

